### ISSUE TITLE
Crash when using CoreClient.Pairing.create

### ISSUE THREAD

**Issue by tomtaila** [WalletConnect/WalletConnectKotlinV2#445]
**Describe the bug**
Calling `CoreClient.Pairing.create` crashes my app despite passing an `onError` callback.
I expect that if there was an issue during creation, the callback would be called but instead it just crashes. 

I know the reason why to, looking at your source code in `PairingClient` here: 
https://github.com/WalletConnect/WalletConnectKotlinV2/blob/develop/androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt#L138

You can see that your logic calls:
`jsonRpcInteractor.unsubscribe(pairingTopic)`

Which itself throws an error, hence causing a crash before the `onError` callback is called.

**SDK Version**
 - Client: Kotlin
 - Version - CORE SDK 1.2.0

**Device (please complete the following information):**
 - Device: Pixel 4 physical device (also has been tested on multiple emulators)
 - OS: Android 13

**Additional context**
```
const val logTag = "WC:Android"

const val projectId = "HIDDEN"
const val relayUrl = "relay.walletconnect.com"
const val serverUrl = "wss://$relayUrl?projectId=$projectId"
val connectionType = ConnectionType.AUTOMATIC // OR ConnectionType.MANUAL
val appMetaData = Core.Model.AppMetaData(
    name = "Wallet Name",
    description = "Wallet Description",
    url = "Wallet Url",
    redirect = "kotlin-dapp-wc:/request",
    icons = emptyList()
)

fun initWalletConnect(app: Application) {
    CoreClient.initialize(
        relayServerUrl = serverUrl,
        connectionType = connectionType,
        application = app,
        metaData = appMetaData
    )
}

fun initWalletConnectSignClient() {
    val init = Sign.Params.Init(core = CoreClient)
    SignClient.initialize(init) { error ->
        Log.d(logTag, "SignClient:Error::$error")
    }
}

fun connect() {
    val pairing = CoreClient.Pairing.create(onError = { error ->
        Log.e("LOGTAG", "$error")
    })
}
```

In my app I call `initWalletConnect` first, `initWalletConnectSignClient` second, and `connect` third. Always crashes.
Core sdk version = 1.2.0
Sign sdk version = 2.0.0

**Comment by TalhaAli00** [comment]
Thanks @tomtaila. We have a PR to address this issue and will hopefully have a release soon with the fix

**Comment by TalhaAli00** [comment]
@tomtaila We just released new versions of our SDKs. You can find a compatibility list here https://github.com/WalletConnect/WalletConnectKotlinV2/tree/master

**Comment by china-mobile2008** [comment]
@TalhaAli00 

still crash

Describe the bug
Calling CoreClient.Pairing.create crashes my app despite passing an onError callback.

02-14 20:00:03.356 27314 27314 E AndroidRuntime: java.lang.IllegalStateException: Creating Pairing failed: java.lang.IllegalStateException: Creating Pairing failed: java.lang.IllegalStateException: Creating Pairing failed: com.walletconnect.android.internal.common.exception.NoRelayConnectionException: No connection available
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at com.walletconnect.android.internal.common.json_rpc.domain.JsonRpcInteractor.checkConnectionWorking(JsonRpcInteractor.kt:57)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at com.walletconnect.android.internal.common.json_rpc.domain.JsonRpcInteractor.subscribe(JsonRpcInteractor.kt:178)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at com.walletconnect.android.internal.common.model.type.JsonRpcInteractorInterface$DefaultImpls.subscribe$default(JsonRpcInteractorInterface.kt:18)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at com.walletconnect.android.pairing.engine.domain.PairingEngine.create(PairingEngine.kt:92)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at com.walletconnect.android.pairing.client.PairingProtocol.create(PairingProtocol.kt:42)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at com.walletconnect.dapp.ui.connect.ConnectViewModel.connectToWallet(ConnectViewModel.kt:63)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at com.walletconnect.dapp.ui.connect.ConnectViewModel.connectToWallet$default(ConnectViewModel.kt:57)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at com.walletconnect.dapp.ui.connect.pairing_generate.PairingGenerationDialogFragment.onViewCreated(PairingGenerationDialogFragment.kt:28)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8668)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)


SDK Version

Client: Kotlin
BOM_VERSION = "1.4.1"
FOUNDATION_VERSION = "1.4.0"
CORE_VERSION = "1.9.1"
SIGN_VERSION = "2.7.1"
AUTH_VERSION = "1.7.1"
CHAT_VERSION = "1.0.0-alpha09"
WEB_3_WALLET = "1.2.1"

Device (please complete the following information):

Device: HUWEI JEF-AN20
OS: Android 10
Additional context
